steps:
  - name: WebScraper
    type: web_scraper_step
    start_url: https://www.town.mizuho.tokyo.jp/kosodate/
    user_agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 12_6_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.112 Safari/537.36
    output_dir: ./output
    progress_file: ./progress.json
    save_every: 5
    skip_flg: yes
  - name: ServiceCatalogCreattor
    type: service_catalog_creator_step
    progress_file: ./progress.json
    output_json_path: ./services.json
    skip_flg: yes
  - name: Html->HTag Layer
    type: html2htaglayer_step
    progress_file: ./progress.json.test.mizuho.one
    output_json_dir: ./output_json_ichijihoiku
    columns_yaml: ./pipeline/columns.yaml
    include_keywords: "児,子育,ファミリー,保育,離乳,教育,食育,ベビー,赤ちゃん,妊,出産,産後"
    skip_flg: no
